---
platform: linux
image: docker:///emccmd/rackhd-cpi
inputs:
  - name: bosh-cpi-release
  - name: stemcell
  - name: bats
run:
  path: bosh-cpi-release/ci/tasks/bats.sh
params:
  CUSTOMIZED_STEMCELL_NAME:        stemcell.tgz
  BOSH_DIRECTOR_PUBLIC_IP:         replace-me
  BOSH_DIRECTOR_PRIVATE_IP:        replace-me
  DIRECTOR_PRIVATE_KEY_DATA:       replace-me
  AGENT_PUBLIC_KEY:                replace-me
  PRIMARY_NETWORK_CIDR:            replace-me
  PRIMARY_NETWORK_GATEWAY:         replace-me
  PRIMARY_NETWORK_RANGE:           replace-me
  PRIMARY_NETWORK_MANUAL_IP:       replace-me
  SECONDARY_STATIC_IP:             replace-me
  BAT_SPEC:                        replace-me
