---
platform: linux
image: docker:///emccmd/rackhd-cpi
inputs:
- name: bosh-cpi-release
- name: stemcell
run:
  path: bosh-cpi-release/ci/tasks/lifecycle.sh
params:
  RACKHD_API_URI:               replace-me
  AGENT_PUBLIC_KEY:             replace-me
  STATIC_IP:                    replace-me
  GATEWAY:                      replace-me
  RACKHD_CPI_LOG_LEVEL:         DEBUG
