---
platform: linux
image: docker:///emccmd/rackhd-cpi
inputs:
- name: bosh-cpi-release
- name: bosh-release
run:
  path: bosh-cpi-release/ci/tasks/setup-director.sh
params:
  BOSH_VSPHERE_DIRECTOR:        replace-me
  BOSH_DIRECTOR_PUBLIC_IP:      replace-me
  BOSH_DIRECTOR_PRIVATE_IP:     replace-me
  BOSH_DIRECTOR_PUBLIC_KEY:     replace-me
  RACKHD_API_URI:               replace-me
  RACKHD_NETWORK:               replace-me
  CPI_RELEASE_NAME:             bosh-rackhd-cpi
  DIRECTOR_DEPLOYMENT_NAME:     bat-director
